services:
  app_angular:
    container_name: app_angular
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network

  app_java:
    container_name: app_java
    image: romerot76/app_java
    build: ./backend/
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    networks:
      - app-network

  java_db:
    container_name: java_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "robertoart23x@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - java_db
    networks:
      - app-network

  netdata:
    container_name: netdata
    image: netdata/netdata
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
      - app-network
    depends_on:
      - app_java

networks:
  app-network:
    driver: bridge

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
